apiVersion: v1
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL21hc3RlcjoyNFV6MldZTVQwdDQ2ZEIzSjFzdEBmbWEtZm1hLXByb3RlZ2UtdHJhY2tlci1kYi10cmFpbmluZy0xNTY1MzIyNzc3LmNzeGNxcjRsZnd3dS5hcC1zb3V0aGVhc3QtMi5yZHMuYW1hem9uYXdzLmNvbTo1NDMyL3Bvc3RncmVzP3NzbG1vZGU9cmVxdWlyZQ==
  ADMIN_NAME: RWF0aGFu
kind: Secret
metadata:
  name: eathan-world-secret
  namespace: fma
type: Opaque