steps:
  - label: ":cut_of_meat: Testing!"
    command: echo pass
    agents:
      queue: "fma-dev-dflt"

  - wait

  - label: ":green_salad: Building & Pushing"
    command: ./ops/scripts/build.sh ${BUILDKITE_BUILD_NUMBER}
    agents:
      queue: "fma-dev-dflt"

  - wait

  - label: ":hamburger: Deploying"
    command: ./ops/scripts/deploy.sh
    agents:
      queue: "europa-preprod-fma"