steps:
  - label: "Testing! :cut_of_meat:"
    command: ./ops/scripts/test.sh
    agents:
      queue: "fma-dev-dflt"

  - wait

  - label: "Building Image & Pushing to ECR :green_salad:"
    command: ./ops/scripts/build.sh
    agents:
      queue: "fma-dev-dflt"

  - wait

  - label: "Deploying :hamburger:"
    command: ./ops/scripts/deploy.sh
    agents:
      queue: "fma-dev-dflt"