steps:
  - label: ":cut_of_meat: Testing"
    command: ./ops/scripts/test.sh
    agents:
      queue: "fma-dev-dflt"

  - wait

  - label: ":green_salad: Building & Pushing"
    command: ./ops/scripts/build.sh
    agents:
      queue: "fma-dev-dflt"

  - wait

  - label: ":hamburger: Deploying"
    command: ./ops/scripts/deploy.sh
    agents:
      queue: "europa-preprod-fma"

  - wait

  - label: ":cup_with_straw: Health Check"
    command: ./ops/scripts/health_check.sh
    agents:
      queue: "fma-dev-dflt"