FROM gradle:latest AS build
WORKDIR /usr/app
COPY . ./
RUN ["gradle", "build"]

FROM openjdk:14-alpine AS build-docker-image
COPY --from=build ./usr/app/build/libs/*.jar /usr/app/
WORKDIR /usr/app
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "Hello-World-1.0-SNAPSHOT.jar"]
RUN echo 'Australia/Melbourne' > /etc/timezone